In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn import linear_model  as lm

In [2]:
df=pd.read_csv('hiring.csv')
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [3]:
df.loc[(df['experience'].isnull()) & (df['interview_score(out of 10)'] == 9), 'experience'] = 'one'

print(df)

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        one                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000


In [4]:
# Update the 'experience' column where 'experience' is 'non' and 'interview_score' is '6'
df.loc[(df['experience'].isnull()) & (df['interview_score(out of 10)'] == 6), 'experience'] = 'zero'

print(df)


  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        one                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000


In [5]:
df.rename(columns={'interview_score(out of 10)': 'interview_score'}, inplace=True)
df.rename(columns={'test_score(out of 10)': 'test_score'}, inplace=True)
df.rename(columns={'salary($)': 'salary'}, inplace=True)
df


experience  test_score  interview_score  salary
0        one         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [6]:
import math
test_median=df['test_score'].median()

In [21]:
df['test_score'].fillna(test_median, inplace=True)

In [14]:
from word2number import w2n
from word2number import w2n

# Convert each value in the 'experience' column to a numeric value
numeric_values = df['experience'].apply(lambda x: w2n.word_to_num(x) if isinstance(x, str) else x)

# Replace the 'experience' column with the converted numeric values
df['experience'] = numeric_values

# Example usage
print(df['experience'])


0     1
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64


In [22]:
df

experience  test_score  interview_score  salary
0           1         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [16]:
reg=lm.LinearRegression()

In [23]:
reg.fit(df[['experience','test_score','interview_score']],df['salary'])

LinearRegression()

In [25]:
reg.predict([[12,10,10]])

C:\Users\Win11\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([91877.25445011])

In [26]:
reg.predict([[2,9,6]])

C:\Users\Win11\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([52963.5525666])

In [28]:
reg.coef_

array([2872.974816  , 1880.52296188, 2075.85769041])

In [30]:
reg.intercept_

17837.750135208218